# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request_target:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      # SERVER_ENDPOINT: http://34.237.55.114:8888
      # AUTHENTICATION_TOKEN: 162G6MgPympbOAqhUy5UhHvL4ozTUSImZJrFTxFiDPF
      # PROJECT_ID: chitchat-YsTb2tdVB
      # SLACK_URL:
      SERVER_ENDPOINT: ${{ secrets.SERVER_ENDPOINT }}
      AUTHENTICATION_TOKEN: ${{ secrets.AUTHENTICATION_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SLACK_URL: ${{ secrets.SLACK_URL }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run Node Script
        run: |
          npm i
          npm run start
